### ISSUE TITLE
Chrome Versions compatibility

### ISSUE THREAD

**Issue by LadyBlackLight** [vtex-apps/checkout-ui-custom#65] opened 2021-06-30 14:44 UTC
Hi, recently we migrate to checkout ui custom, but most of the users of the site have an old version of Chrome and in all cases the checkout don't show nothing, the users can't buy on the checkout, what we can do for it?

**Comment by lucvysk** [comment] 2021-06-30 15:50
Hi @LadyBlackLight , do you have the version of the chrome? Operating system?

**Comment by LadyBlackLight** [comment] 2021-06-30 16:02
Hi, only have the versions of Chrome:

72.0.3626.122
78.0.3904.106
78.0.3904.113
79.0.3945.119
79.0.3945.123
80.0.3987.122
80.0.3987.132

*Vanessa Hernández Maldonado*
*Ingeniera en Multimedia UMNG*
(+57) 316 698 14 80

**Comment by lucvysk** [comment] 2021-06-30 18:18
Hi @LadyBlackLight , sorry again, what is the store ? 
Does it happens with the checkout without customizations too?

**Comment by LadyBlackLight** [comment] 2021-06-30 20:07
@lucvysk hi, this is the store: https://www.titan.com.pa/

**Comment by lucvysk** [comment] 2021-07-01 12:52
@LadyBlackLight , we did some test and the problem isn't the app but the custom added js. The specific line is this one: 
` :243       const logistics = vtexjs?.checkout?.orderForm?.shippingData?.logisticsInfo;`
I'm closing the issue, ok?!

**Closed by lucvysk** 2021-07-01 12:52 UTC
